stages:
  - build
  - test

build-job:
    stage: build
    script:
      - cd proxy/socks5
      - go build binaries/ server.go
    tags:
      - proxy
    artifacts:
      paths:
        - binaries/server

test-job:
  stage: test
  script:
    - echo "test job is running"
    - ls binaries/
  dependencies:
    - build-job
