stages:
  - build
  - test

build-job:
    stage: build
    script:
      - cd proxy/socks5
      - go build -o binaries/ server.go
    tags:
      - proxy
    artifacts:
      paths:
        - proxy/socks5/binaries/server

run-server-job:
  stage: test
  script:
    - echo "test job is running"
    - timeout 60 ./proxy/socks5/binaries/server || exit 0
  dependencies:
    - build-job
  tags:
    - proxy

curl-job:
  stage: test
  script:
    - output=$(curl --socks5 5.42.99.137:10100 -U test:test 2ip.ru)
    - |
      if [ "$output" = "5.42.99.137" ]; then
        echo "Success"
      else
        echo "IP address doesn't match expected value"
        exit 1
      fi
  dependencies:
    - run-server-job

deploy:
  stage: deploy
  script:
    - echo "Authenticating to Vault..."
    - export VAULT_TOKEN=$(vault write -format=json auth/jwt/login role=gitlab-role jwt=$JWT_TOKEN | jq -r .auth.client_token)
    - echo "Accessing secrets from Vault..."
    - export SECRET=$(vault kv get -field=ip secret/data/gitlab)
    - echo "The secret is: $SECRET"