stages:
  - build
  - test

build-job:
    stage: build
    script:
      - cd proxy/socks5
      - go build -o binaries/ server.go
    tags:
      - proxy
    artifacts:
      paths:
        - proxy/socks5/binaries/server

run-server-job:
  stage: test
  script:
    - echo "test job is running"
    - ./proxy/socks5/binaries/server
    - sleep 10
    - pkill server
  dependencies:
    - build-job
  tags:
    - proxy

curl-job:
  stage: test
  script:
    - output=$(curl --socks5 5.42.99.137:10100 -U test:test 2ip.ru)
    - |
      if [ "$output" = "5.42.99.137" ]; then
        echo "Success"
      else
        echo "IP address doesn't match expected value"
        exit 1
      fi
  dependencies:
    - run-server-job