stages:
  - build
  - test
  - deploy

build-job:
    stage: build
    script:
      - cd proxy/socks5
      - go build -o binaries/ server.go
    tags:
      - proxy
    artifacts:
      paths:
        - proxy/socks5/binaries/server

run-server-job:
  stage: test
  script:
    - echo "test job is running"
    - timeout 60 ./proxy/socks5/binaries/server || exit 0
  dependencies:
    - build-job
  tags:
    - proxy

curl-job:
  stage: test
  script:
    - output=$(curl --socks5 5.42.99.137:10100 -U test:test 2ip.ru)
    - |
      if [ "$output" = "5.42.99.137" ]; then
        echo "Success"
      else
        echo "IP address doesn't match expected value"
        exit 1
      fi
  dependencies:
    - run-server-job

deploy-job:
  stage: deploy
  image: vault:latest
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://gitlab.com
  script:
    - apt-get update && apt-get install -y jq curl
    - |
      VAULT_TOKEN=$(curl -s -H "Authorization: Bearer $VAULT_ID_TOKEN" \
        "${VAULT_ADDR}/v1/auth/jwt/login" | jq -r '.auth.client_token')
      export VAULT_TOKEN
    - SECRET=$(vault kv get -field=ip secret/gitlab)
    - echo $SECRET